version: "3.8"

networks:
  publication-net:
    external: true

volumes:
  prometheus_data:
  grafana_data:
  logs_data:

services:
  grafana-alloy:
    image: grafana/alloy:latest
    hostname: alloy
    ports:
      - "12345:12345"
      - "4318:4318"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - logs_data:/var/log/app
      - ./config.alloy:/etc/alloy/config.alloy:ro
    command: [ "run", "/etc/alloy/config.alloy" ]
    networks:
      - publication-net
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M
#  prometheus:
#    image: prom/prometheus:latest
#    hostname: prometheus
#    ports:
#      - "9090:9090"
#    command:
#      - "--config.file=/etc/prometheus/prometheus.yml"
#      - "--storage.tsdb.path=/prometheus"
#      - '--storage.tsdb.retention.time=1d'
#      - "--web.enable-lifecycle"
#    volumes:
#      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
#      - prometheus_data:/prometheus
#    networks:
#      - publication-net
#    deploy:
#      resources:
#        limits:
#          memory: 150M
#          cpus: "0.3"
#
#  grafana:
#    image: grafana/grafana:latest
#    hostname: grafana
#    ports:
#      - "3000:3000"
#    environment:
#      - GF_SECURITY_ADMIN_USER=admin
#      - GF_SECURITY_ADMIN_PASSWORD=admin
#    volumes:
#      - grafana_data:/var/lib/grafana
#    depends_on:
#      - prometheus
#    networks:
#      - publication-net
#    deploy:
#      resources:
#        limits:
#          memory: 100M
#          cpus: "0.2"
